apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: thrift-rb
  namespace: ctslater
subjects:
- kind: ServiceAccount
  name: thrift-sa
  namespace: ctslater
roleRef:
  kind: Role
  name: thrift-driver
  apiGroup: rbac.authorization.k8s.io
