apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ctslater
  name: thrift-driver
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
