# This is pretty similar to thrift-svc, but
# this should be all the internal ports that
# don't get exposed to the outside world.
apiVersion: v1
kind: Service
metadata:
  name: spark-thrift-driver-svc
spec:
  clusterIP: None
  selector:
    app: spark-thrift-driver
  ports:
    - name: spark
      protocol: TCP
      port: 4444
      targetPort: 4444
    - name: blockmgr
      protocol: TCP
      port: 7123
      targetPort: 7123
